### ISSUE TITLE
invalid master/tasks/main.yml - undefined variable

### ISSUE THREAD

**Issue by screeley44** [gluster/gluster-kubernetes#62] opened 2016-12-08 20:44 UTC
Here is a new one
```
TASK [setup] *******************************************************************
ok: [master]

TASK [master : kubeadm init] ***************************************************
fatal: [master]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'ipv4'\n\nThe error appears to have been in '/home/screeley/git/gluster-kubernetes-dev/fix_metalink_error/gluster-kubernetes/vagrant/roles/master/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: kubeadm init\n  ^ here\n"}
	to retry, use: --limit @/home/screeley/git/gluster-kubernetes-dev/fix_metalink_error/gluster-kubernetes/vagrant/site.retry

PLAY RECAP *********************************************************************
master                     : ok=24   changed=22   unreachable=0    failed=1   
node0                      : ok=23   changed=22   unreachable=0    failed=0   
node1                      : ok=23   changed=22   unreachable=0    failed=0   
node2                      : ok=23   changed=22   unreachable=0    failed=0   
node3                      : ok=23   changed=22   unreachable=0    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by screeley44** [comment] 2016-12-09 19:07
I have been able to reproduce this yet, will leave open a bit longer, but if I can't reproduce will close

**Comment by grantnicholas** [comment] 2017-02-21 21:52
I ran into this same issue. The property: `ansible_eth1.ipv4.address` was failing for me because I did not have the network interface `eth1` defined on my machine. To confirm this try `ifconfig | grep eth1`.

**Comment by jarrpa** [comment] 2017-09-13 18:32
Closing this issue. We can reopen it if someone can reproduce it reliably and look into a proper fix or at least a workaround.

**Closed by jarrpa** 2017-09-13 18:32 UTC
