### ISSUE TITLE
Error: No Space with heketi:dev image

### ISSUE THREAD

**Issue by dougbtv** [gluster/gluster-kubernetes#369] opened 2017-10-12 13:29 UTC
Currently, using `gk-deploy` -- if I am to use the `heketi/heketi:dev` tag (as is default in gluster-kubernetes) I am presented with gk-deploy failing with: `Error: no space`. If I change the yaml resource definitions to point at the `heketi/heketi:5` image tag -- it completes without error. (This is a follow up issue from #363 )

I run gk-deploy like so:

```
./gk-deploy -n gluster -w 900 -g -y
```

And the output from that command is as follows:

```
Using Kubernetes CLI.
NAME      STATUS    AGE
gluster   Active    29s
Using namespace \"gluster\".
Checking that heketi pod is not running ... OK
serviceaccount \"heketi-service-account\" created
clusterrolebinding \"heketi-sa-view\" created
node \"kube-node-1\" labeled
node \"kube-node-2\" labeled
node \"kube-node-3\" labeled
daemonset \"glusterfs\" created
Waiting for GlusterFS pods to start ... OK
service \"deploy-heketi\" created
deployment \"deploy-heketi\" created
Waiting for deploy-heketi pod to start ... OK
Creating cluster ... ID: dbf97520031abff522fa64ea05a25179
Creating node kube-node-1 ... ID: 850ffe0c688b921171125e454ed03e70
Adding device /dev/vdb ... OK
Creating node kube-node-2 ... ID: 1fc2b1a08627e3679c60a39489cb7aee
Adding device /dev/vdb ... OK
Creating node kube-node-3 ... ID: ffaff3aca6c006383440e9fa7b667994
Adding device /dev/vdb ... OK
heketi topology loaded.
Error: No space
```

The `topology.json` file I'm using (with both either `:dev` or `:5` tags) is:

```
{
  "clusters": [
    {
      "nodes": [
                {
          "node": {
            "hostnames": {
              "manage": [
                "kube-node-1"
              ],
              "storage": [
                "192.168.1.145"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/vdb"
          ]
        },                {
          "node": {
            "hostnames": {
              "manage": [
                "kube-node-2"
              ],
              "storage": [
                "192.168.1.67"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/vdb"
          ]
        },                {
          "node": {
            "hostnames": {
              "manage": [
                "kube-node-3"
              ],
              "storage": [
                "192.168.1.69"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/vdb"
          ]
        }              ]
    }
  ]
}
```

I'm currently deploying gluster-kubernetes on a Kubernetes version 1.8.0 cluster (however, this did occur previously with a 1.7.5 cluster, for what it's worth)

```
[centos@kube-master deploy]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jarrpa** [comment] 2017-10-12 16:00
@dougbtv Can you also paste the heketi logs from when the (not very useful) error message occurs?

**Comment by dougbtv** [comment] 2017-10-12 20:42
Sure thing, a bit of a huge log, but...

```
[centos@kube-master ~]$ kubectl get pods -n gluster --show-all
NAME                             READY     STATUS    RESTARTS   AGE
deploy-heketi-599b67479b-w5g5x   1/1       Running   0          3m
glusterfs-b78mx                  1/1       Running   0          6m
glusterfs-nqvbm                  1/1       Running   0          6m
glusterfs-x2xhl                  1/1       Running   0          6m
[centos@kube-master ~]$ kubectl logs -n gluster deploy-heketi-599b67479b-w5g5x
Heketi v5.0.0-79-gc8daa55
[heketi] INFO 2017/10/12 20:39:13 Loaded kubernetes executor
[heketi] INFO 2017/10/12 20:39:13 Loaded simple allocator
[heketi] INFO 2017/10/12 20:39:13 GlusterFS Application Loaded
Listening on port 8080
[negroni] Started GET /clusters
[negroni] Completed 200 OK in 287.067µs
[negroni] Started POST /clusters
[negroni] Completed 201 Created in 28.583129ms
[negroni] Started POST /nodes
[sshexec] INFO 2017/10/12 20:39:20 Check Glusterd service status in node kube-node-1
[kubeexec] DEBUG 2017/10/12 20:39:20 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: systemctl status glusterd
Result: ● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-10-12 20:37:09 UTC; 2min 10s ago
  Process: 50 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 51 (glusterd)
   CGroup: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd60f94b4_af8c_11e7_89b0_525400e3ead3.slice/docker-f30d81defa452e7baacc99d36101ec03f85e45309bb6e316703cea83e83e9b10.scope/system.slice/glusterd.service
           └─51 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Oct 12 20:37:06 kube-node-1 systemd[1]: Starting GlusterFS, a clustered file-system server...
Oct 12 20:37:09 kube-node-1 systemd[1]: Started GlusterFS, a clustered file-system server.
[heketi] INFO 2017/10/12 20:39:20 Adding node kube-node-1
[negroni] Completed 202 Accepted in 143.096376ms
[asynchttp] INFO 2017/10/12 20:39:20 asynchttp.go:125: Started job 88cab5cf4e8282450e9383fd09ad5b3a
[negroni] Started GET /queue/88cab5cf4e8282450e9383fd09ad5b3a
[negroni] Completed 200 OK in 35.906µs
[heketi] INFO 2017/10/12 20:39:20 Added node 0359531bcd632676e151159a992cfdfd
[asynchttp] INFO 2017/10/12 20:39:20 asynchttp.go:129: Completed job 88cab5cf4e8282450e9383fd09ad5b3a in 27.110786ms
[negroni] Started GET /queue/88cab5cf4e8282450e9383fd09ad5b3a
[negroni] Completed 303 See Other in 97.752µs
[negroni] Started GET /nodes/0359531bcd632676e151159a992cfdfd
[negroni] Completed 200 OK in 468.593µs
[negroni] Started POST /devices
[heketi] INFO 2017/10/12 20:39:20 Adding device /dev/vdb to node 0359531bcd632676e151159a992cfdfd
[negroni] Completed 202 Accepted in 15.269003ms
[asynchttp] INFO 2017/10/12 20:39:20 asynchttp.go:125: Started job dffe0e9ff34663c6f7ebdf3503a8ed69
[negroni] Started GET /queue/dffe0e9ff34663c6f7ebdf3503a8ed69
[negroni] Completed 200 OK in 21.227µs
[kubeexec] DEBUG 2017/10/12 20:39:20 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: pvcreate --metadatasize=128M --dataalignment=256K /dev/vdb
Result:   Physical volume "/dev/vdb" successfully created.
[kubeexec] DEBUG 2017/10/12 20:39:21 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: vgcreate vg_4faa5a22e752435ba777c04f21a9c73e /dev/vdb
Result:   Volume group "vg_4faa5a22e752435ba777c04f21a9c73e" successfully created
[kubeexec] DEBUG 2017/10/12 20:39:21 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: vgdisplay -c vg_4faa5a22e752435ba777c04f21a9c73e
Result:   vg_4faa5a22e752435ba777c04f21a9c73e:r/w:772:-1:0:0:0:-1:0:1:1:10350592:4096:2527:0:2527:vdFDF5-q1Fm-HD0X-c9rI-I8U6-KhRv-wlYwYM
[sshexec] DEBUG 2017/10/12 20:39:21 /src/github.com/heketi/heketi/executors/sshexec/device.go:141: Size of /dev/vdb in kube-node-1 is 10350592
[heketi] INFO 2017/10/12 20:39:21 Added device /dev/vdb
[asynchttp] INFO 2017/10/12 20:39:21 asynchttp.go:129: Completed job dffe0e9ff34663c6f7ebdf3503a8ed69 in 481.904257ms
[negroni] Started GET /queue/dffe0e9ff34663c6f7ebdf3503a8ed69
[negroni] Completed 204 No Content in 73.959µs
[negroni] Started POST /nodes
[sshexec] INFO 2017/10/12 20:39:21 Check Glusterd service status in node kube-node-1
[kubeexec] DEBUG 2017/10/12 20:39:21 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: systemctl status glusterd
Result: ● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-10-12 20:37:09 UTC; 2min 12s ago
  Process: 50 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 51 (glusterd)
   CGroup: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd60f94b4_af8c_11e7_89b0_525400e3ead3.slice/docker-f30d81defa452e7baacc99d36101ec03f85e45309bb6e316703cea83e83e9b10.scope/system.slice/glusterd.service
           └─51 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Oct 12 20:37:06 kube-node-1 systemd[1]: Starting GlusterFS, a clustered file-system server...
Oct 12 20:37:09 kube-node-1 systemd[1]: Started GlusterFS, a clustered file-system server.
[heketi] INFO 2017/10/12 20:39:21 Adding node kube-node-2
[negroni] Completed 202 Accepted in 132.711325ms
[asynchttp] INFO 2017/10/12 20:39:21 asynchttp.go:125: Started job 18202c76eeaba434785e86fda859b323
[sshexec] INFO 2017/10/12 20:39:21 Probing: kube-node-1 -> 192.168.1.142
[negroni] Started GET /queue/18202c76eeaba434785e86fda859b323
[negroni] Completed 200 OK in 26.31µs
[negroni] Started GET /queue/18202c76eeaba434785e86fda859b323
[negroni] Completed 200 OK in 34.267µs
[negroni] Started GET /queue/18202c76eeaba434785e86fda859b323
[negroni] Completed 200 OK in 31.81µs
[kubeexec] DEBUG 2017/10/12 20:39:22 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: gluster peer probe 192.168.1.142
Result: peer probe: success. 
[sshexec] INFO 2017/10/12 20:39:22 Setting snapshot limit
[negroni] Started GET /queue/18202c76eeaba434785e86fda859b323
[negroni] Completed 200 OK in 53.509µs
[kubeexec] DEBUG 2017/10/12 20:39:22 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: gluster --mode=script snapshot config snap-max-hard-limit 14
Result: snapshot config: snap-max-hard-limit for System set successfully
[heketi] INFO 2017/10/12 20:39:22 Added node 97a0a16e3a8f28ceb5d3ca765443b48d
[asynchttp] INFO 2017/10/12 20:39:22 asynchttp.go:129: Completed job 18202c76eeaba434785e86fda859b323 in 884.164089ms
[negroni] Started GET /queue/18202c76eeaba434785e86fda859b323
[negroni] Completed 303 See Other in 77.975µs
[negroni] Started GET /nodes/97a0a16e3a8f28ceb5d3ca765443b48d
[negroni] Completed 200 OK in 253.639µs
[negroni] Started POST /devices
[heketi] INFO 2017/10/12 20:39:23 Adding device /dev/vdb to node 97a0a16e3a8f28ceb5d3ca765443b48d
[negroni] Completed 202 Accepted in 25.843144ms
[asynchttp] INFO 2017/10/12 20:39:23 asynchttp.go:125: Started job 363deb8082c6201fd0e2c84a34da21e3
[negroni] Started GET /queue/363deb8082c6201fd0e2c84a34da21e3
[negroni] Completed 200 OK in 27.9µs
[kubeexec] DEBUG 2017/10/12 20:39:23 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-2 Pod: glusterfs-x2xhl Command: pvcreate --metadatasize=128M --dataalignment=256K /dev/vdb
Result:   Physical volume "/dev/vdb" successfully created.
[kubeexec] DEBUG 2017/10/12 20:39:23 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-2 Pod: glusterfs-x2xhl Command: vgcreate vg_3888cbcbfc8a5ea209ad676ae5aa7030 /dev/vdb
Result:   Volume group "vg_3888cbcbfc8a5ea209ad676ae5aa7030" successfully created
[kubeexec] DEBUG 2017/10/12 20:39:23 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-2 Pod: glusterfs-x2xhl Command: vgdisplay -c vg_3888cbcbfc8a5ea209ad676ae5aa7030
Result:   vg_3888cbcbfc8a5ea209ad676ae5aa7030:r/w:772:-1:0:0:0:-1:0:1:1:10350592:4096:2527:0:2527:3AQVPA-w7I3-04fE-IVI4-qEsn-uRUh-w6fQyF
[sshexec] DEBUG 2017/10/12 20:39:23 /src/github.com/heketi/heketi/executors/sshexec/device.go:141: Size of /dev/vdb in kube-node-2 is 10350592
[heketi] INFO 2017/10/12 20:39:23 Added device /dev/vdb
[asynchttp] INFO 2017/10/12 20:39:23 asynchttp.go:129: Completed job 363deb8082c6201fd0e2c84a34da21e3 in 563.433394ms
[negroni] Started GET /queue/363deb8082c6201fd0e2c84a34da21e3
[negroni] Completed 204 No Content in 42.291µs
[negroni] Started POST /nodes
[sshexec] INFO 2017/10/12 20:39:24 Check Glusterd service status in node kube-node-1
[kubeexec] DEBUG 2017/10/12 20:39:24 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: systemctl status glusterd
Result: ● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-10-12 20:37:09 UTC; 2min 14s ago
  Process: 50 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 51 (glusterd)
   CGroup: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd60f94b4_af8c_11e7_89b0_525400e3ead3.slice/docker-f30d81defa452e7baacc99d36101ec03f85e45309bb6e316703cea83e83e9b10.scope/system.slice/glusterd.service
           └─51 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Oct 12 20:37:06 kube-node-1 systemd[1]: Starting GlusterFS, a clustered file-system server...
Oct 12 20:37:09 kube-node-1 systemd[1]: Started GlusterFS, a clustered file-system server.
[heketi] INFO 2017/10/12 20:39:24 Adding node kube-node-3
[negroni] Completed 202 Accepted in 131.271901ms
[asynchttp] INFO 2017/10/12 20:39:24 asynchttp.go:125: Started job 3f9af15a596cb3cf74f4818b855f3fb7
[sshexec] INFO 2017/10/12 20:39:24 Probing: kube-node-1 -> 192.168.1.237
[negroni] Started GET /queue/3f9af15a596cb3cf74f4818b855f3fb7
[negroni] Completed 200 OK in 466.997µs
[negroni] Started GET /queue/3f9af15a596cb3cf74f4818b855f3fb7
[negroni] Completed 200 OK in 37.271µs
[negroni] Started GET /queue/3f9af15a596cb3cf74f4818b855f3fb7
[negroni] Completed 200 OK in 41.119µs
[kubeexec] DEBUG 2017/10/12 20:39:24 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: gluster peer probe 192.168.1.237
Result: peer probe: success. 
[sshexec] INFO 2017/10/12 20:39:24 Setting snapshot limit
[negroni] Started GET /queue/3f9af15a596cb3cf74f4818b855f3fb7
[negroni] Completed 200 OK in 87.588µs
[negroni] Started GET /queue/3f9af15a596cb3cf74f4818b855f3fb7
[negroni] Completed 200 OK in 52.341µs
[kubeexec] DEBUG 2017/10/12 20:39:25 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-1 Pod: glusterfs-nqvbm Command: gluster --mode=script snapshot config snap-max-hard-limit 14
Result: snapshot config: snap-max-hard-limit for System set successfully
[heketi] INFO 2017/10/12 20:39:25 Added node 709b9698cc9484b0224758b91be7b668
[asynchttp] INFO 2017/10/12 20:39:25 asynchttp.go:129: Completed job 3f9af15a596cb3cf74f4818b855f3fb7 in 1.176803021s
[negroni] Started GET /queue/3f9af15a596cb3cf74f4818b855f3fb7
[negroni] Completed 303 See Other in 51.364µs
[negroni] Started GET /nodes/709b9698cc9484b0224758b91be7b668
[negroni] Completed 200 OK in 270.44µs
[negroni] Started POST /devices
[heketi] INFO 2017/10/12 20:39:25 Adding device /dev/vdb to node 709b9698cc9484b0224758b91be7b668
[negroni] Completed 202 Accepted in 53.298375ms
[asynchttp] INFO 2017/10/12 20:39:25 asynchttp.go:125: Started job 56838d80437a6c4204d797c305c3b88c
[negroni] Started GET /queue/56838d80437a6c4204d797c305c3b88c
[negroni] Completed 200 OK in 36.711µs
[kubeexec] DEBUG 2017/10/12 20:39:25 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-3 Pod: glusterfs-b78mx Command: pvcreate --metadatasize=128M --dataalignment=256K /dev/vdb
Result:   Physical volume "/dev/vdb" successfully created.
[kubeexec] DEBUG 2017/10/12 20:39:25 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-3 Pod: glusterfs-b78mx Command: vgcreate vg_5e981163bf7e7ea7cafb5b81c92d002e /dev/vdb
Result:   Volume group "vg_5e981163bf7e7ea7cafb5b81c92d002e" successfully created
[kubeexec] DEBUG 2017/10/12 20:39:26 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kube-node-3 Pod: glusterfs-b78mx Command: vgdisplay -c vg_5e981163bf7e7ea7cafb5b81c92d002e
Result:   vg_5e981163bf7e7ea7cafb5b81c92d002e:r/w:772:-1:0:0:0:-1:0:1:1:10350592:4096:2527:0:2527:GAHr3S-tuZV-XStL-8MsF-6dyf-Ovip-eYegaf
[sshexec] DEBUG 2017/10/12 20:39:26 /src/github.com/heketi/heketi/executors/sshexec/device.go:141: Size of /dev/vdb in kube-node-3 is 10350592
[heketi] INFO 2017/10/12 20:39:26 Added device /dev/vdb
[asynchttp] INFO 2017/10/12 20:39:26 asynchttp.go:129: Completed job 56838d80437a6c4204d797c305c3b88c in 594.62233ms
[negroni] Started GET /queue/56838d80437a6c4204d797c305c3b88c
[negroni] Completed 204 No Content in 31.323µs
[negroni] Started GET /clusters/e41d98add407254dcb70d54fbab219d8
[negroni] Completed 200 OK in 269.658µs
[negroni] Started GET /clusters
[negroni] Completed 200 OK in 75.083µs
[negroni] Started GET /clusters/e41d98add407254dcb70d54fbab219d8
[negroni] Completed 200 OK in 161.062µs
[negroni] Started POST /volumes
[negroni] Completed 202 Accepted in 181.879µs
[asynchttp] INFO 2017/10/12 20:39:26 asynchttp.go:125: Started job 100131f24b8731b052fc13abbef3c028
[heketi] INFO 2017/10/12 20:39:26 Creating volume e2577bd999db84790fae298d5e09162a
[negroni] Started GET /queue/100131f24b8731b052fc13abbef3c028
[negroni] Completed 200 OK in 28.665µs
[heketi] ERROR 2017/10/12 20:39:26 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:290: Volume being ask to be created, but there are no clusters configured
[heketi] ERROR 2017/10/12 20:39:26 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:149: Failed to create volume: No space
[asynchttp] INFO 2017/10/12 20:39:26 asynchttp.go:129: Completed job 100131f24b8731b052fc13abbef3c028 in 15.163176ms
[negroni] Started GET /queue/100131f24b8731b052fc13abbef3c028
[negroni] Completed 500 Internal Server Error in 53.383µs
```

**Comment by jarrpa** [comment] 2017-10-12 21:09
@dougbtv Can you exec into the heketi container and use the command `heketi-cli -s http://localhost:8080 --user admin --key '' topology info` to get the list of nodes and volumes heketi knows about? There are also `node info` and `volume info` subcommands you can run to see if they show anything useful.

**Comment by dougbtv** [comment] 2017-10-13 18:04
You got it, here's what it looks like. Interestingly enough `volume list` command comes up empty but exits 0. Here's the output:

```
[centos@kube-master ~]$ kubectl exec -n gluster -it deploy-heketi-599b67479b-fhtmx -- /bin/bash
[root@deploy-heketi-599b67479b-fhtmx /]# heketi-cli -s http://localhost:8080 --user admin --key '' topology info
Error: unknown flag: --key
[root@deploy-heketi-599b67479b-fhtmx /]# heketi-cli -s http://localhost:8080 --user admin topology info         

Cluster Id: b884fb2b77530df03c9486907ff5802b

    File:  false
    Block: false

    Volumes:

    Nodes:

  Node Id: 8b8e5ee87c7f37d3db289951b41d98bb
  State: online
  Cluster Id: b884fb2b77530df03c9486907ff5802b
  Zone: 1
  Management Hostname: kube-node-2
  Storage Hostname: 192.168.1.61
  Devices:
    Id:46e9fd3fbc1acca835c906c2ea1af2c1   Name:/dev/vdb            State:online    Size (GiB):9       Used (GiB):0       Free (GiB):9       
      Bricks:

  Node Id: 9192068ea150c2e9a29295061489e6c3
  State: online
  Cluster Id: b884fb2b77530df03c9486907ff5802b
  Zone: 1
  Management Hostname: kube-node-3
  Storage Hostname: 192.168.1.74
  Devices:
    Id:742746766aeb89c50c0f372c51277ee6   Name:/dev/vdb            State:online    Size (GiB):9       Used (GiB):0       Free (GiB):9       
      Bricks:

  Node Id: 98f19e4f07e67734ca6fb04c15756ae4
  State: online
  Cluster Id: b884fb2b77530df03c9486907ff5802b
  Zone: 1
  Management Hostname: kube-node-1
  Storage Hostname: 192.168.1.138
  Devices:
    Id:55292c11a9982a16ce356e2b34aa40b0   Name:/dev/vdb            State:online    Size (GiB):9       Used (GiB):0       Free (GiB):9       
      Bricks:



[root@deploy-heketi-599b67479b-fhtmx /]# heketi-cli -s http://localhost:8080 --user admin node info 8b8e5ee87c7f37d3db289951b41d98bb
Node Id: 8b8e5ee87c7f37d3db289951b41d98bb
State: online
Cluster Id: b884fb2b77530df03c9486907ff5802b
Zone: 1
Management Hostname: kube-node-2
Storage Hostname: 192.168.1.61
Devices:
Id:46e9fd3fbc1acca835c906c2ea1af2c1   Name:/dev/vdb            State:online    Size (GiB):9       Used (GiB):0       Free (GiB):9       

[root@deploy-heketi-599b67479b-fhtmx /]# heketi-cli -s http://localhost:8080 --user admin node info 9192068ea150c2e9a29295061489e6c3
Node Id: 9192068ea150c2e9a29295061489e6c3
State: online
Cluster Id: b884fb2b77530df03c9486907ff5802b
Zone: 1
Management Hostname: kube-node-3
Storage Hostname: 192.168.1.74
Devices:
Id:742746766aeb89c50c0f372c51277ee6   Name:/dev/vdb            State:online    Size (GiB):9       Used (GiB):0       Free (GiB):9       

[root@deploy-heketi-599b67479b-fhtmx /]# heketi-cli -s http://localhost:8080 --user admin node info 98f19e4f07e67734ca6fb04c15756ae4
Node Id: 98f19e4f07e67734ca6fb04c15756ae4
State: online
Cluster Id: b884fb2b77530df03c9486907ff5802b
Zone: 1
Management Hostname: kube-node-1
Storage Hostname: 192.168.1.138
Devices:
Id:55292c11a9982a16ce356e2b34aa40b0   Name:/dev/vdb            State:online    Size (GiB):9       Used (GiB):0       Free (GiB):9       





[root@deploy-heketi-599b67479b-fhtmx /]# heketi-cli -s http://localhost:8080 --user admin volume list       
[root@deploy-heketi-599b67479b-fhtmx /]# echo $?
0

```

**Comment by jarrpa** [comment] 2017-10-13 18:16
Hm... dang. This sounds like a heketi issue. Can you open a new issue in the heketi repo including the following from what you've already provided here:
* Problem statement, including the fact that heketi:5 doesn't have the issue
* gk-deploy output
* topology file
* topology info output
* heketi log

**Comment by dougbtv** [comment] 2017-10-13 18:46
Absolutely, thanks for fishing through it Jose.

**Comment by dougbtv** [comment] 2017-10-13 19:24
I've got it filed in the heketi/heketi github repo as reference.

**Comment by patrickstjohn** [comment] 2017-11-01 19:01
We were able to workaround this by moving back to the heketi/heketi:latest container. You have to modify deploy-heketi-deployment.json as well as heketi-storage.json (as created by heketi-cli setup-openshift-heketi-storage)

**Comment by obnoxxx** [comment] 2017-11-03 00:19
The problem is "Block: False" and "File: False" in the Cluster info.
They should actually both default to True.

If they are set to false, the behavior is as expected.

**Comment by obnoxxx** [comment] 2017-11-03 00:30
Oooh! Where is the heketi-cli coming from which is used in the gk-deploy-run?

**Comment by obnoxxx** [comment] 2017-11-03 00:32
I think this might be the root cause: a slightly older heketi-cli that does not know about the new cluster flags. The bug would be that the logic to set the defaults should be in the server, not in the client....

**Comment by obnoxxx** [comment] 2017-11-03 17:32
I guess we figured it out. Bug remains in heketi and we can close this one.

@dougbtv please reopen if I missed anything.

**Closed by obnoxxx** 2017-11-03 17:32 UTC

**Comment by fzagarzazu** [comment] 2018-04-20 23:34
I ran into the same problem, I ended up doing the same thing @patrickstjohn mentioned above.

If somebody runs into the same problem again, this is how I was cleaning things up before attempting again, in each server: 
```
# ./gk-deploy -g --abort 
# dmsetup remove_all   # In each server.
# dmsetup ls
# rm -fr /var/lib/glusterd/vols/* # In each server.
# rm -fr /var/lib/heketi/* # In each server.
# wipefs -a /dev/<device> # In each server.
```
