### ISSUE TITLE
thin: Required device-mapper target(s) not detected in your kernel

### ISSUE THREAD

**Issue by webwurst** [gluster/gluster-kubernetes#19] opened 2016-11-16 14:14 UTC
I am hitting the following error when executing `heketi-cli setup-openshift-heketi-storage`:
```
Error: Unable to execute command on glusterfs1-1373000839-qq9jv:   /usr/sbin/modprobe failed: 1
  Cannot read thin-pool target version.
  thin: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
```
On the hosts there is `Ubuntu 16.04.1 LTS` installed.

What are the  prerequisites for Heketi/Glusterfs to create volumes?

**Comment by webwurst** [comment] 2016-11-16 14:20
Ok, in my case I needed to execute `modprobe dm_thin_pool` on all nodes to resolve this.

**Comment by jarrpa** [comment] 2016-11-18 17:28
Closing the issue since it seems it worked itself out. :) Feel free to comment and re-open if I'm mistaken.

**Closed by jarrpa** 2016-11-18 17:28 UTC

**Comment by sheerun** [comment] 2017-03-01 02:33
@jarrpa Could you reopen this? @webwurst suggestion indeed worked out, but this is a reproducible issue that needs to be automated somehow I guess.. Maybe this issue needs to be raised somewhere else, like kubelet or something

**Comment by jarrpa** [comment] 2017-03-01 15:14
PR #155 should provide a mechanism for automating this, I believe.
