### ISSUE TITLE
stuck on heketi topoloy loaded

### ISSUE THREAD

**Issue by 13567436138** [gluster/gluster-kubernetes#459] opened 2018-04-11 05:10 UTC
stuck on heketi topoloy loaded.

**Comment by 13567436138** [comment] 2018-04-11 05:34
/usr/local/bin/kubectl -n kube-system exec -i deploy-heketi-6bf856646b-6rpv9 -- heketi-cli -s http://localhost:8080 --user admin --secret '' setup-openshift-heketi-storage --listfile=/tmp/heketi-storage.json  2>&

**Comment by 13567436138** [comment] 2018-04-11 05:34
this command stuck

**Comment by nixpanic** [comment] 2018-04-11 09:55
Can you provide further details? The distribution that you are using and
logs or output of the command would be a start.

**Comment by renich** [comment] 2018-04-16 22:03
Hello @nixpanic 

I am having this same issue. Here's my log output: 

```
root@k8s0:~/src/gluster-kubernetes/deploy# ./gk-deploy -n kube-system -c kubectl -gvy ~/topology.json
Using Kubernetes CLI.

Checking status of namespace matching 'kube-system':
kube-system   Active    24m
Using namespace "kube-system".
Checking for pre-existing resources...
  GlusterFS pods ... 
Checking status of pods matching '--selector=glusterfs=pod':

Timed out waiting for pods matching '--selector=glusterfs=pod'.
not found.
  deploy-heketi pod ... 
Checking status of pods matching '--selector=deploy-heketi=pod':

Timed out waiting for pods matching '--selector=deploy-heketi=pod'.
not found.
  heketi pod ... 
Checking status of pods matching '--selector=heketi=pod':

Timed out waiting for pods matching '--selector=heketi=pod'.
not found.
  gluster-s3 pod ... 
Checking status of pods matching '--selector=glusterfs=s3-pod':

Timed out waiting for pods matching '--selector=glusterfs=s3-pod'.
not found.
Creating initial resources ... kubectl -n kube-system create -f /root/src/gluster-kubernetes/deploy/kube-templates/heketi-service-account.yaml 2>&1
serviceaccount "heketi-service-account" created
kubectl -n kube-system create clusterrolebinding heketi-sa-view --clusterrole=edit --serviceaccount=kube-system:heketi-service-account 2>&1
clusterrolebinding.rbac.authorization.k8s.io "heketi-sa-view" created
kubectl -n kube-system label --overwrite clusterrolebinding heketi-sa-view glusterfs=heketi-sa-view heketi=sa-view
clusterrolebinding.rbac.authorization.k8s.io "heketi-sa-view" labeled
OK
Marking 'glusterfs0.mia.cloudsigma.com' as a GlusterFS node.
kubectl -n kube-system label nodes glusterfs0.mia.cloudsigma.com storagenode=glusterfs --overwrite 2>&1
node "glusterfs0.mia.cloudsigma.com" labeled
Marking 'glusterfs1.mia.cloudsigma.com' as a GlusterFS node.
kubectl -n kube-system label nodes glusterfs1.mia.cloudsigma.com storagenode=glusterfs --overwrite 2>&1
node "glusterfs1.mia.cloudsigma.com" labeled
Marking 'glusterfs2.mia.cloudsigma.com' as a GlusterFS node.
kubectl -n kube-system label nodes glusterfs2.mia.cloudsigma.com storagenode=glusterfs --overwrite 2>&1
node "glusterfs2.mia.cloudsigma.com" labeled
Deploying GlusterFS pods.
sed -e 's/storagenode\: glusterfs/storagenode\: 'glusterfs'/g' /root/src/gluster-kubernetes/deploy/kube-templates/glusterfs-daemonset.yaml | kubectl -n kube-system create -f - 2>&1
daemonset.extensions "glusterfs" created
Waiting for GlusterFS pods to start ... 
Checking status of pods matching '--selector=glusterfs=pod':
glusterfs-2mfcb   1/1       Running   0         56s
glusterfs-thpsb   1/1       Running   0         56s
glusterfs-wgcg4   1/1       Running   0         56s
OK
kubectl -n kube-system create secret generic heketi-config-secret --from-file=private_key=/dev/null --from-file=./heketi.json --from-file=topology.json=/root/topology.json
secret "heketi-config-secret" created
kubectl -n kube-system label --overwrite secret heketi-config-secret glusterfs=heketi-config-secret heketi=config-secret
secret "heketi-config-secret" labeled
sed -e 's/\${HEKETI_EXECUTOR}/kubernetes/' -e 's#\${HEKETI_FSTAB}#/var/lib/heketi/fstab#' -e 's/\${HEKETI_ADMIN_KEY}//' -e 's/\${HEKETI_USER_KEY}//' /root/src/gluster-kubernetes/deploy/kube-templates/deploy-heketi-deployment.yaml | kubectl -n kube-system create -f - 2>&1
service "deploy-heketi" created
deployment.extensions "deploy-heketi" created
Waiting for deploy-heketi pod to start ... 
Checking status of pods matching '--selector=deploy-heketi=pod':
deploy-heketi-6c7d48f8b-q2r6b   1/1       Running   0         36s
OK
Determining heketi service URL ... Flag --show-all has been deprecated, will be removed in an upcoming release
OK
kubectl -n kube-system exec -i deploy-heketi-6c7d48f8b-q2r6b -- heketi-cli -s http://localhost:8080 --user admin --secret '' topology load --json=/etc/heketi/topology.json 2>&1
Creating cluster ... ID: 8887d612bd3b00d9a0ec67a0aade7f6a
Allowing file volumes on cluster.
Allowing block volumes on cluster.
Creating node glusterfs0.mia.cloudsigma.com ... ID: 615468dfa3a1f21b5655e4544f7bd5c2
Adding device /dev/vdb ... OK
Creating node glusterfs1.mia.cloudsigma.com ... ID: b2cdd3559d1e3f14166fdb741dfee38e
Adding device /dev/vdb ... OK
Creating node glusterfs2.mia.cloudsigma.com ... ID: 5179e82a4b7d53ceb667a600c086364e
Adding device /dev/vdb ... OK
heketi topology loaded.
kubectl -n kube-system exec -i deploy-heketi-6c7d48f8b-q2r6b -- heketi-cli -s http://localhost:8080 --user admin --secret '' setup-openshift-heketi-storage --listfile=/tmp/heketi-storage.json  2>&1
Error: Failed to allocate new volume: No space
command terminated with exit code 255
Failed on setup openshift heketi storage
This may indicate that the storage must be wiped and the GlusterFS nodes must be reset.
```
The problem is related to heketi thinking there is no space left. My blocks are 500 GB each and this is a brand new cluster.

**Comment by renich** [comment] 2018-04-16 22:12
Just as a tip, I've found out the problem, I think. For some reason, in the deployment, one of the nodes claims to have a /dev/vdb with `Free (GiB): 0`:

```
[root@deploy-heketi-6c7d48f8b-q2r6b /]# heketi-cli -s http://localhost:8080 --user admin --secret ''  topology info

Cluster Id: 8887d612bd3b00d9a0ec67a0aade7f6a

    File:  true
    Block: true

    Volumes:

    Nodes:

	Node Id: 5179e82a4b7d53ceb667a600c086364e
	State: online
	Cluster Id: 8887d612bd3b00d9a0ec67a0aade7f6a
	Zone: 1
	Management Hostnames: glusterfs2.mia.cloudsigma.com
	Storage Hostnames: 192.168.77.102
	Devices:
		Id:01e6d14537c0a3085ad5358b91c47ca5   Name:/dev/vdb            State:online    Size (GiB):0       Used (GiB):0       Free (GiB):0       
			Bricks:

	Node Id: 615468dfa3a1f21b5655e4544f7bd5c2
	State: online
	Cluster Id: 8887d612bd3b00d9a0ec67a0aade7f6a
	Zone: 1
	Management Hostnames: glusterfs0.mia.cloudsigma.com
	Storage Hostnames: 192.168.77.100
	Devices:
		Id:b593e403f9e9df1d31193487d6068864   Name:/dev/vdb            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
			Bricks:

	Node Id: b2cdd3559d1e3f14166fdb741dfee38e
	State: online
	Cluster Id: 8887d612bd3b00d9a0ec67a0aade7f6a
	Zone: 1
	Management Hostnames: glusterfs1.mia.cloudsigma.com
	Storage Hostnames: 192.168.77.101
	Devices:
		Id:a62d64b99f1f8fb7934b6ea183d9b1dd   Name:/dev/vdb            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
			Bricks:

```

This was totally my bad. I've created one of the drives as a 1 GB drive by mistake. I will correct the error, pvresize it and see what happens.

**Comment by renich** [comment] 2018-04-16 23:29
Just to confirm that everything worked fine once I `dd if=/dev/zero of=/dev/vdb`, as well as clearing the required directories and restarted. 

The deployment went fine.

**Comment by jarrpa** [comment] 2018-04-18 11:44
@renich Good to hear!

Given that the OP has been completely unresponsive for a week, closing this issue.

**Closed by jarrpa** 2018-04-18 11:44 UTC
