### ISSUE TITLE
GKE 1.6, no dm_thin_pool module available

### ISSUE THREAD

**Issue by blakebarnett** [gluster/gluster-kubernetes#249] opened 2017-04-11 06:24 UTC
I'm not sure what needs to happen for this to work on a GKE cluster running k8s 1.6, there is no dm_thin_pool module on the host, I guess they just didn't add the glusterfs-client package and kernel modules to the system image?

**Comment by blakebarnett** [comment] 2017-04-11 06:27
Nevermind, just read the fine print when creating a new cluster.  Need to use the `container-vm` node image.

**Comment by davidberardozzi** [comment] 2017-04-21 13:51
Thank you for this great work.

I am also trying to setup a glusterfs cluster on google container engine with Kubernetes 1.6.1 and the cos image.

I know there is a note that encourages the user to use the container-vm image instead of cos when creating a kubernetes cluster through the google console ui. But on the other hand gluster deployment is "almost" working apart for the missing module dm_thin_pool that causes it to fail at the end.

Even if it is closed, Is there is any chance or anything to try in order to make it work ?

**Comment by jarrpa** [comment] 2017-04-21 14:21
@davidberardozzi Refering to your question at the end: In what sense? What do you mean by "make it work", and in what context?

**Comment by davidberardozzi** [comment] 2017-04-21 15:59
@jarrpa, ok sorry, let me be more specific:

The `gk-deploy` script went well until it tries to execute `heketi-cli -s http://${heketi_service} setup-openshift-heketi-storage`

```
Error: Unable to execute command on glusterfs-xxxxx:   /usr/sbin/modprobe failed: 1
thin: Required device-mapper target(s) not detected in your kernel.
Run `lvcreate --help' for more information.
Failed on setup openshift heketi storage
```

I did try using `modeprobe dm_thin_pool` to each Kubernetes node, But it won't work on the cos image type because, to my knowledge, this module is not found by modprobe and there seems to be no way to install additional packages.

My question is: do you think that I can do or try something in order to overcome this error ?

As @blakebarnett said, it looks like there is a missing dependancy into the google container optimized os image. If this is really the case I suppose I'll just have to wait until the image gets updated with the missing packages. Thank you

**Comment by jarrpa** [comment] 2017-04-21 16:21
@davidberardozzi Ah. No, I am not aware of anything that can be done to work around this error. :( heketi currently requires the use of LVM to modify the storage devices under its control. Your best options would be to raise an Issue either in https://github.com/heketi/heketi do see if we can remove the requirement for `dm_thin_pool` or whatever project handles the maintenance of the optimized container image you want to use.

**Comment by humblec** [comment] 2017-04-22 10:27
@davidberardozzi @blakebarnett the best bet would be getting that module in the container optimized os image , as we need that module for various options. May be u can open an issue agasint GKE.

**Comment by davidberardozzi** [comment] 2017-04-22 11:13
With pleasure. But to be honest, I cannot figure out yet where I should open the issue. Will try on chromium os project

**Comment by davidberardozzi** [comment] 2017-04-25 08:06
The issue is filed here: [Issue 715009](https://bugs.chromium.org/p/chromium/issues/detail?id=715009).

**Comment by davidberardozzi** [comment] 2017-05-11 13:13
Things are moving see [comment 2](https://bugs.chromium.org/p/chromium/issues/detail?id=715009#c2)

**Comment by jarrpa** [comment] 2017-05-11 18:46
@davidberardozzi Woohoo! :)

**Comment by adityakali** [comment] 2017-06-01 18:34
/cc @jingxu97

Cross-posting from [crbug.com/715009](http://crbug.com/715009) :

[cos-dev-60-9540-0-0](https://cloud.google.com/container-optimized-os/docs/release-notes#cos-dev-60-9540-0-0) and newer images now have `DM_THIN_PROVISIONING` enabled. You can choose this image while creating your kubernetes cluster by setting following env vars before doing kube_up.sh:
```
export KUBE_OS_DISTRIBUTION=cos
export KUBE_GCE_MASTER_PROJECT=cos-cloud
export KUBE_GCE_MASTER_IMAGE=cos-dev-60-9540-0-0
export KUBE_GCE_NODE_PROJECT=cos-cloud
export KUBE_GCE_NODE_IMAGE=cos-dev-60-9540-0-0
```
So now `modprobe dm_thin_pool` works and loads the module. Though you will have to manually run it on all nodes because of issue https://github.com/gluster/gluster-kubernetes/issues/19.

I tried following the instructions at https://github.com/gluster/gluster-kubernetes and https://github.com/heketi/heketi/wiki/Kubernetes-Integration.
Everything went fine until I ran into issue https://github.com/heketi/heketi/issues/764 (heketi-cli uses xfs to configure the glusterfs, but Container-Optimized OS only supports ext4).

Kubernetes supports ext4 based glusterfs volumes already. So I think it should be possible to hack around heketi-cli to use ext4. I can try and experiment with it.

**Comment by jarrpa** [comment] 2017-09-14 23:17
As there is now an image with the required kernel module, I'll be closing this issue. :)

If there's still a need for pursuing other things like using ext4 on the bricks, please feel free to open a new issue!

**Closed by jarrpa** 2017-09-14 23:17 UTC
